### ISSUE TITLE
9. Разработка мобильной версии блога

### ISSUE THREAD

**Issue by IanaKhitsko** [ksuchernaya/blog_req#11]
Для какой мобильной ОС? Уточните. Если и Apple и Android, например, то это два разных приложения, и заказчик должен понимать, что все это выливается в деньги.

**Comment by ksuchernaya** [comment]
Под мобильной версией имеется ввиду оптимизация веб-сайта для мобильных устройств, но не разработка отдельных приложений под разные мобильные ОС.
См. пункт 10
