### ISSUE TITLE
Посты пользователя

### ISSUE THREAD

**Issue by ZameAlex** [ksuchernaya/blog_req#12]
Если пользователи могут писать свои посты, это разве будет блог библиотеки? Скорее это форум будет.
https://github.com/ksuchernaya/blog_req/blob/fb7aae7e06debb044d63a547cc2a4121f3c7acdf/blog_requirenments.txt#L29

**Comment by ksuchernaya** [comment]
Под пользователями имеется ввиду не "пользователи библиотеки", а "пользователи системы".
Тоесть посты могут писать сотрудники библиотеки, которые будут "пользователями системы"
