### ISSUE TITLE
Создание блога

### ISSUE THREAD

**Issue by ZameAlex** [ksuchernaya/blog_req#2]
Необходимо создание полностью нового блога на новой платформе, или идёт речь о переработке старой системы?

https://github.com/ksuchernaya/blog_req/blob/61bb06e908272f43e8f59d4d71613580767e1d42/blog_requirenments.txt#L4

**Comment by ksuchernaya** [comment]
Идет речь о создании нового блога, так как старая версия блога не удовлетворяет заказчика.
См. пункт 1
