### ISSUE TITLE
Разделы для общения

### ISSUE THREAD

**Issue by ZameAlex** [ksuchernaya/blog_req#3]
Не совсем понятно, как организовать разные разделы для общения в рамках блога. Под общением имеется ввиду комментирование постов?

https://github.com/ksuchernaya/blog_req/blob/61bb06e908272f43e8f59d4d71613580767e1d42/blog_requirenments.txt#L5-L8

**Comment by ksuchernaya** [comment]
Улучшила объяснение по этому замечанию.
Разделы для общения -> Разделы для постов
Т. е. в разных разделах можно публиковать тематические посты.
