### ISSUE TITLE
Второстепенное требование - стабильность

### ISSUE THREAD

**Issue by ZameAlex** [ksuchernaya/blog_req#4]
Не согласен с тем, что стабильность - это второстепенное требование, так как тогда нет особого смысла в реализации всех остальных требований, если это приведёт к проблемам в работе системы.
https://github.com/ksuchernaya/blog_req/blob/61bb06e908272f43e8f59d4d71613580767e1d42/blog_requirenments.txt#L14

**Comment by ksuchernaya** [comment]
Согласна с замечанием, перенесла требования по стабильности в "Первостепенные требования".
См. пункт 9
