### ISSUE TITLE
Комментарии к постам

### ISSUE THREAD

**Issue by ZameAlex** [ksuchernaya/blog_req#6]
Необходимо уточнить: все ли посты можно будет комментировать и будет ли возможность удалять комментарии.

https://github.com/ksuchernaya/blog_req/blob/61bb06e908272f43e8f59d4d71613580767e1d42/blog_requirenments.txt#L10

**Comment by ksuchernaya** [comment]
Уточнение:
комментировать все посты (свои и других пользователей)
удалять комментарии можно
См. пункт 6-7
