### ISSUE TITLE
6. Обеспечение стабильности системы

### ISSUE THREAD

**Issue by IanaKhitsko** [ksuchernaya/blog_req#9]
Любое требование должно быть сформулировано таким образом, чтобы его можно было протестировать. Как обеспечивать стабильность будем? Каким образом это проверить? Дайте минимальные нагрузочные требования в числах...

**Comment by ksuchernaya** [comment]
Переформулировала требования для последующей возможности их тестирования.
См. пункт 9 - требования к стабильности системы
